spring:
  application:
    name: springboot-mybatis-quickstart
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/web01
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
mybatis.configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl