spring:
  application:
    name: Tlias
  #配置数据库的连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
mybatis.configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#驼峰命名的开关
mybatis.configuration.map-underscore-to-camel-case: true